services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"  # Map the development server port
    volumes:
      - ./frontend:/app # Mount your frontend source code
    environment:
      - CHOKIDAR_USEPOLLING=true # Important for file watching on some systems
      - NODE_ENV=development
    networks:
      - app-network
    depends_on:
      - backend

  backend: # Include backend service in dev compose as well
    build: ./backend
    ports:
      - "8123:8123"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    image: pgvector/pgvector:pg13
    ports:
      - 5432:5432
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge